=== mozilla/gcp-ingestion/ingestion-beam/src/main/resources/telemetry.pioneer-study.4.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "application": {
      "additionalProperties": false,
      "properties": {
        "architecture": {
          "type": "string"
        },
        "buildId": {
          "pattern": "^[0-9]{10}",
          "type": "string"
        },
        "channel": {
          "type": "string"
        },
        "displayVersion": {
          "pattern": "^[0-9]{2,3}\\.",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "platformVersion": {
          "pattern": "^[0-9]{2,3}\\.",
          "type": "string"
        },
        "vendor": {
          "type": "string"
        },
        "version": {
          "pattern": "^[0-9]{2,3}\\.",
          "type": "string"
        },
        "xpcomAbi": {
          "type": "string"
        }
      },
      "required": [
        "architecture",
        "buildId",
        "channel",
        "name",
        "platformVersion",
        "version",
        "vendor",
        "xpcomAbi"
      ],
      "type": "object"
    },
    "creationDate": {
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
      "type": "string"
    },
    "id": {
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
      "type": "string"
    },
    "payload": {
      "description": "",
      "properties": {
        "encryptedData": {
          "description": "JOSE/JWE encrypted payload.",
          "type": "string"
        },
        "encryptionKeyId": {
          "description": "JOSE/JWK key id, e.g. pioneer-20170520.",
          "type": "string"
        },
        "pioneerId": {
          "description": "Custom pioneer id, must not be Telemetry clientId",
          "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
          "type": "string"
        },
        "schemaName": {
          "description": "Name of a schema used for validation of the encryptedData",
          "maxLength": 100,
          "minLength": 1,
          "pattern": "^\\S+$",
          "type": "string"
        },
        "schemaNamespace": {
          "description": "The namespace of the schema used for validation and routing to a dataset.",
          "maxLength": 100,
          "minLength": 1,
          "pattern": "^\\S+$",
          "type": "string"
        },
        "schemaVersion": {
          "description": "Integer version number of the schema",
          "minimum": 1,
          "type": "integer"
        },
        "studyName": {
          "description": "Name of a particular study. Usually the addon_id.",
          "maxLength": 100,
          "minLength": 1,
          "pattern": "^\\S+$",
          "type": "string"
        }
      },
      "required": [
        "encryptedData",
        "encryptionKeyId",
        "pioneerId",
        "schemaNamespace",
        "studyName",
        "schemaName",
        "schemaVersion"
      ],
      "title": "pioneer-study",
      "type": "object"
    },
    "type": {
      "description": "doc_type, restated",
      "enum": [
        "pioneer-study"
      ],
      "type": "string"
    },
    "version": {
      "maximum": 4,
      "minimum": 4,
      "type": "integer"
    }
  },
  "required": [
    "application",
    "creationDate",
    "id",
    "payload",
    "type",
    "version"
  ],
  "title": "pioneer-study",
  "type": "object"
}

=== mozilla/gcp-ingestion/ingestion-beam/src/test/resources/pioneer/telemetry.pioneer-study.4.sample.pass.json
{
  "type": "pioneer-study",
  "id": "9af045aa-80ca-e743-92de-b31431abc547",
  "creationDate": "2020-04-24T20:04:10.285Z",
  "version": 4,
  "application": {
    "architecture": "x86-64",
    "buildId": "20200415104457",
    "name": "Firefox",
    "version": "77.0a1",
    "displayVersion": "77.0a1",
    "vendor": "Mozilla",
    "platformVersion": "77.0a1",
    "xpcomAbi": "x86_64-gcc3",
    "channel": "default"
  },
  "payload": {
    "encryptedData": "eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTI1NkdDTSIsImVwayI6eyJjcnYiOiJQLTI1NiIsImV4dCI6dHJ1ZSwia3R5IjoiRUMiLCJ4IjoiSFN5dXBzM1RWdEJ3V3JTTnFKMi1ycnd1LVVKdFVnbmtMTW9hOGJBNUVlayIsInkiOiItQmdTbzE3ZUZFRGlncC03emtEX0xEQVNVZ0xjdFNEZGk5NG9rYm1EYTkwIn19..Ri7NaZFlcHmg6IS4.ZnYhkv26B2g7Z7eXrIHGH69F_MxG99eLyiXdRzdZ8L2Y.OJ6eKSYuG3pcU5gEJo2thA",
    "encryptionKeyId": "pioneer-v2-study",
    "schemaNamespace": "pioneer-v2-study",
    "schemaName": "event",
    "schemaVersion": 1,
    "pioneerId": "9af045aa-80ca-e743-92de-b31431abc547",
    "studyName": "pioneer-v2-example@example.com"
  }
}

=== mozilla/gcp-ingestion/ingestion-beam/src/test/resources/pioneer/bug-1691807.deletion-request.valid.study-bar.ciphertext.json
{
  "type": "pioneer-study",
  "id": "9af045aa-80ca-e743-92de-b31431abc547",
  "creationDate": "2020-04-24T20:04:10.285Z",
  "version": 4,
  "application": {
    "architecture": "x86-64",
    "buildId": "20200415104457",
    "name": "Firefox",
    "version": "77.0a1",
    "displayVersion": "77.0a1",
    "vendor": "Mozilla",
    "platformVersion": "77.0a1",
    "xpcomAbi": "x86_64-gcc3",
    "channel": "default"
  },
  "payload": {
    "encryptedData": "eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTI1NkdDTSIsImVwayI6eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6ImhXUWdlTTVWOXZid2ZfZFV4V3hwWFMxdmVIb2g3dHlmVUdhN3NBOFRzWnciLCJ5IjoiMVR0MXRqVDYxdzRyWm9sSllGd0djYnlQNkcxRjUtM0pMd2pfam1Ua1JKSSJ9LCJraWQiOiIzcDhTQ3R5cmEwdV9CLWhMRTdaTm5GcjNFZDBjMTVLdkNEcUxrN2Rpblc4IiwidHlwIjoiSldFIn0..tOiU2P5Fc3ER1U1Y.rrOuQai8iSTIcTT_OrvdGKNBj06Eu9KdM_ewjWZ8st0iEjT8Jsby1lsIjSQkwJsfWOoACZ2um-OBAAiFesIbesdWz0ldD9UTeSGcJQ6Uyw.-obDckIMilQ4WHYjeXUU9g",
    "encryptionKeyId": "study-bar",
    "schemaNamespace": "study-bar",
    "schemaName": "deletion-request",
    "schemaVersion": 1,
    "pioneerId": "9af045aa-80ca-e743-92de-b31431abc547",
    "studyName": "pioneer-v2-example@example.com"
  }
}

=== mozilla/gcp-ingestion/ingestion-beam/src/test/resources/pioneer/enrollment.sample.json
{
    "type": "pioneer-study",
    "id": "716a5d6f-3a68-da42-8a1e-2a220960f72b",
    "creationDate": "2020-08-19T20:49:43.382Z",
    "version": 4,
    "application": {
      "architecture": "x86-64",
      "buildId": "20200819100116",
      "name": "Firefox",
      "version": "81.0a1",
      "displayVersion": "81.0a1",
      "vendor": "Mozilla",
      "platformVersion": "81.0a1",
      "xpcomAbi": "x86_64-gcc3",
      "channel": "default"
    },
    "payload": {
      "encryptedData": "eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTI1NkdDTSIsImVwayI6eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6IjNyTXBPRnlCVHFzMXBseUF1cFo0dGYzS0JiQ0hMU0lQTlNWZVROdl9ZblkiLCJ5IjoieWg5bzJrZmhGU2FKd2RzQ1ZQZHdJb1N1QmhPbHU2MkF4X1NlWjV3ZFQ3VSJ9fQ..7-fq-hzz5nuiUk-h.UkNtJDV8ZJX5VlvEiDJObVhY3Ghrxv_111luHBOZhSOwUwwEkwqqhK_xHuF1x-YnPgagafl2tbnIn5Dy3kq79xCOyGmyqaJpTDmalg.0qmesf29ki5HV5S5waiViA",
      "schemaVersion": 1,
      "schemaName": "enrollment",
      "schemaNamespace": "pioneer-debug",
      "encryptionKeyId": "debug",
      "pioneerId": "64a7f717-e2ce-0d4b-a36d-91c860345082",
      "studyName": "pioneer-v2-example@mozilla.org"
    }
  }
